apiVersion: apps/v1
kind: Deployemnt
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLables:
      app: mongodb
  template:
    metadta:
      labels:
        app: mongodb
      sepc: 
        containers:
        - name:  mongodb
          image:  mongo
          ports:
          - cobtainerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value:
          - name: MONGO_INITDB_ROOT_PASSWORD
            value:
        
          